# Generated by Django 5.2.6 on 2025-12-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTacheApp', '0003_alter_tache_options_tache_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='notify_interval_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
