# Generated by Django 5.2.6 on 2025-12-10 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_employee_notification_enabled_and_more'),
        ('GestionTacheApp', '0005_tache_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tache_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='GestionTacheApp.tache')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='uploaded_task_documents', to='EmployeeApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TacheNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task_notes', to='EmployeeApp.employee')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='GestionTacheApp.tache')),
            ],
        ),
    ]
