# Generated by Django 5.2.6 on 2025-12-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmployeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('idTache', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('Pending', 'En attente'), ('Done', 'Terminée')], default='Pending', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='taches', to='EmployeApp.employe')),
            ],
            options={
                'ordering': ['employee', 'order', 'date_echeance'],
            },
        ),
    ]
