# Generated by Django 5.2.6 on 2025-12-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTacheApp', '0006_tachecollaboration_collab_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='collaboration_status',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='collaborator',
        ),
        migrations.AlterField(
            model_name='tachecollaboration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
