# Generated by Django 5.2.6 on 2025-12-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='notification_interval_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
