# Generated by Django 5.2.6 on 2025-11-14 18:08

import EmployeeApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='nom ne peut contenir que des lettres, des espaces et des virgules.', regex='^[a-zA-Z\\s,]+$')])),
                ('prenom', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='prenom ne peut contenir que des lettres, des espaces et des virgules.', regex='^[a-zA-Z\\s,]+$')])),
                ('service', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Medecin', 'Medecin'), ('Infirmier', 'Infirmier'), ('Gestionnaire de Materiel', 'Gestionnaire de Materiel')], max_length=50)),
                ('dateEmbauche', models.DateField()),
                ('login', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, validators=[EmployeeApp.models.verify_email])),
                ('MotDePasse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 8 chiffres.', regex='^\\d{8}$')])),
            ],
        ),
    ]
