# Generated by Django 5.2.6 on 2025-12-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('medecin', 'Médecin'), ('infirmiere', 'Infirmière'), ('administrateur', 'Administrateur')], max_length=20)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_embauche', models.DateField()),
                ('service', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
