# Generated by Django 5.2.8 on 2025-11-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('medecin_id', models.IntegerField()),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('statut', models.CharField(choices=[('prévu', 'Prévu'), ('annulé', 'Annulé'), ('terminé', 'Terminé')], default='prévu', max_length=20)),
            ],
        ),
    ]
