# Generated by Django 5.2.8 on 2025-11-19 22:00

import RendezVousApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RendezVousApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='date_rdv',
            field=models.DateField(validators=[RendezVousApp.models.validate_date_future]),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='heure_rdv',
            field=models.TimeField(validators=[RendezVousApp.models.validate_heure]),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin_id',
            field=models.IntegerField(validators=[RendezVousApp.models.validate_medecin_id]),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient_id',
            field=models.IntegerField(validators=[RendezVousApp.models.validate_patient_id]),
        ),
    ]
