# Generated by Django 5.2.8 on 2025-11-19 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientApp', '0001_initial'),
        ('RendezVousApp', '0002_alter_rendezvous_date_rdv_alter_rendezvous_heure_rdv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='patient_id',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='PatientApp.patient'),
        ),
    ]
