# Generated by Django 5.2.8 on 2025-12-10 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeApp', '0001_initial'),
        ('RendezVousApp', '0004_alter_rendezvous_medecin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin_id',
            field=models.ForeignKey(db_column='medecin_id', limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_medecin', to='EmployeApp.employe'),
        ),
    ]
