# Generated by Django 5.2.8 on 2025-12-10 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeApp', '0001_initial'),
        ('PatientApp', '0002_patient_num_tel'),
        ('RendezVousApp', '0005_alter_rendezvous_medecin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='medecin_id',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_medecin', to='EmployeApp.employe'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='PatientApp.patient'),
        ),
    ]
