# Generated by Django 5.2.6 on 2025-11-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTacheApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
