# Generated by Django 5.2.6 on 2025-12-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionTacheApp', '0002_alter_tache_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tache',
            options={'ordering': ['employee', 'order', 'date_echeance']},
        ),
        migrations.AddField(
            model_name='tache',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
