# Generated by Django 5.2.6 on 2025-12-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_employee_notification_enabled_and_more'),
        ('GestionTacheApp', '0004_tache_notify_interval_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collab_taches', to='EmployeeApp.employee'),
        ),
    ]
