# Generated by Django 5.2.8 on 2025-11-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterielMedical',
            fields=[
                ('IdMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=50)),
                ('Reference', models.CharField(max_length=50)),
                ('Etat', models.CharField(choices=[('EN_SERVICE', 'EN_SERVICE'), ('EN_MAINTENANCE', 'EN_MAINTENANCE'), ('HORS_SERVICE', 'HORS_SERVICE'), ('EN_PRET', 'EN_PRET')], default='EN_SERVICE', max_length=20)),
                ('Quantite', models.PositiveIntegerField()),
                ('PrixAchat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DateAcquisition', models.DateField()),
                ('DateExpiration', models.DateField()),
            ],
        ),
    ]
