# Generated by Django 5.2.8 on 2025-11-12 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('role', models.CharField(choices=[('MEDECIN', 'Médecin'), ('INFIRMIER', 'Infirmier'), ('ADMIN', 'Administratif'), ('TECHNICIEN', 'Technicien'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Rôle')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Login')),
                ('motDePasse', models.CharField(max_length=128, verbose_name='Mot de passe')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Numéro de téléphone invalide. Format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('dateEmbauche', models.DateField(verbose_name="Date d'embauche")),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
