# Generated by Django 5.2.8 on 2025-11-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='motDePasse',
            field=models.CharField(max_length=256, verbose_name='Mot de passe'),
        ),
    ]
