# Generated by Django 5.2.8 on 2025-11-20 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_employes', '0002_alter_employe_motdepasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='etat',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('CONGE', 'En congé'), ('SUSPENSION', 'Suspendu')], default='ACTIF', max_length=20, verbose_name='État'),
        ),
        migrations.AddField(
            model_name='employe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employes/photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='telephone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone'),
        ),
    ]
