# Generated by Django 5.2.8 on 2025-11-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materielmedical',
            name='QuantiteInitiale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
