# Generated by Django 5.2.8 on 2025-11-26 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialsApp', '0002_materielmedical_quantiteinitiale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batiment', models.CharField(max_length=50)),
                ('etage', models.CharField(blank=True, max_length=10)),
                ('salle', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='materielmedical',
            name='emplacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MaterialsApp.emplacement'),
        ),
        migrations.AddField(
            model_name='materielmedical',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MaterialsApp.fournisseur'),
        ),
        migrations.CreateModel(
            name='HistoriqueMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('MAINTENANCE', 'Maintenance'), ('PRET', 'Mise en prêt'), ('RETOUR', 'Retour de prêt')], default='MODIFICATION', max_length=20)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('champ_modifie', models.CharField(blank=True, max_length=50)),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialsApp.materielmedical')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
