# Generated by Django 5.2.8 on 2025-11-26 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialsApp', '0003_emplacement_fournisseur_materielmedical_emplacement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiquemateriel',
            old_name='date_modification',
            new_name='date_action',
        ),
        migrations.RenameField(
            model_name='historiquemateriel',
            old_name='ancienne_valeur',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='historiquemateriel',
            name='champ_modifie',
        ),
        migrations.RemoveField(
            model_name='historiquemateriel',
            name='nouvelle_valeur',
        ),
        migrations.RemoveField(
            model_name='historiquemateriel',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='historiquemateriel',
            name='action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('MAINTENANCE', 'Maintenance'), ('PRET', 'Mise en prêt'), ('RETOUR', 'Retour de prêt')], max_length=20),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('EXPIRE', 'Expiration proche'), ('STOCK', 'Stock faible'), ('MAINTENANCE', 'Maintenance requise'), ('SECURITE', 'Alerte sécurité')], max_length=20)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialsApp.materielmedical')),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprunteur', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('date_pret', models.DateField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_reelle', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RETOURNE', 'Retourné'), ('RETARD', 'En retard')], default='EN_COURS', max_length=20)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialsApp.materielmedical')),
            ],
        ),
    ]
