# Generated by Django 5.2.8 on 2025-11-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialsApp', '0004_rename_date_modification_historiquemateriel_date_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='priorite',
            field=models.CharField(choices=[('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('BASSE', 'Basse')], default='MOYENNE', max_length=10),
        ),
        migrations.AddField(
            model_name='alerte',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EN_COURS', 'En cours de traitement'), ('RESOLUE', 'Résolue')], default='ACTIVE', max_length=15),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('MAINTENANCE', 'Maintenance requise'), ('STOCK', 'Stock bas'), ('EXPIRE', 'Expiration'), ('PANNE', 'Panne'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
