# Generated by Django 5.2.8 on 2025-12-10 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='num_tel',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être un numéro tunisien valide à 8 chiffres.', regex='^[2-9]\\d{7}$')]),
        ),
    ]
