# Generated by Django 5.2.6 on 2025-11-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='login',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
