# Generated by Django 5.2.6 on 2025-12-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_remove_employee_id_alter_employee_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='notification_interval_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
